name: Connect to GCP and List Instances 2

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: lesson-087
  PROJECT_ID: 'github-actions-384318'

jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider:  'projects/221742135820/locations/global/workloadIdentityPools/gitlab-demo-wip-88/providers/gitlab-identity-provider'
        service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'

    # List the instances in the project
    - name: List Instances
      run: |-
        gcloud compute instances list --project github-actions-384318
        
    # Read secret     
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud secrets versions access "latest" --secret "testing-secret"
        
        
        
              
    - name: Build Docker Image
      env:
        PROJECT_ID: github-actions-384318
      run: docker build -t $IMAGE_NAME:latest . #build the docker image
        
    - name: Configure Docker Client
      run:  |-
        gcloud auth configure-docker --quiet #authenticate to gcr
        gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Container Registry GCR
      env:
        GIT_TAG:  v0.1.0
        PROJECT_ID: github-actions-384318
      #tag docker image to gcr image format then push to gcr
      run: |-        
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

        
        
    
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v1.2
        PROJECT_ID: github-actions-384318
      run: |-        
        docker tag $IMAGE_NAME:latest europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
    
