name: Get secrets from secret manager
on: 
  workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/221742135820/locations/global/workloadIdentityPools/githubactions/providers/githubactions'
        service_account: 'githubactions@github-actions-384318.iam.gserviceaccount.com'


