name: Connect to GCP and List Instances

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: lesson-087
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider:  "projects/1076063715960/locations/global/workloadIdentityPools/my-pool"
        service_account: 'test-wif@wif-testing-412508.iam.gserviceaccount.com'

    # List the instances in the project
    - name: List Instances
      run: |-
        gcloud compute instances list --project github-actions-384318
        
    # Read secret     
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud secrets versions access "latest" --secret "testing-secret"
